#ifndef PARAMETERS_H
#define PARAMETERS_H
double  Altitude;
double  ASScstr;
double  AttenMitch;
double  BundHeight;
double  Ca;
double  CO2Cp;
double  CO2Exp;
double  CO2Slopetr;
double  CoeffAssimSla;
double  CoefficientQ10;
double  CoeffInternodeMass;
double  CoeffInternodeNum;
double  CoeffLeafDeath;
double  CoeffLeafWLRatio;
double  CoeffPanicleMass;
double  CoeffPanSinkPop;
double  CoeffResCapacityInternode;
double  CoeffReserveSink;
double  CoeffRootMassPerVolMax;
double  CoeffTillerDeath;
double  CoeffTransplantingShock;
double  DensityField;
double  DensityNursery;
double  DEVcstr;
double  DurationNursery;
double  EpaisseurProf;
double  EpaisseurSurf;
double  ExcessAssimToRoot;
double  FTSWIrrig;
double  HaunCritTillering;
double  HumFC;
double  HumPF;
double  HumSat;
double  IcTillering;
double  InternodeLengthMax;
double  IrrigAuto;
double  IrrigAutoResume;
double  IrrigAutoStop;
double  IrrigAutoTarget;
double  KcMax;
double  KCritSterCold1;
double  KCritSterCold2;
double  KCritSterFtsw1;
double  KCritSterFtsw2;
double  KCritSterHeat1;
double  KCritSterHeat2;
double  KCritStressCold1;
double  KCritStressCold2;
double  Kdf;
double  KPar;
double  KRespInternode;
double  KRespMaintLeaf;
double  KRespMaintRoot;
double  KRespMaintSheath;
double  KRespPanicle;
double  KTempMaint;
double  Latitude;
double  LeafLengthMax;
double  LifeSavingDrainage;
double  Mulch;
double  PanStructMassMax;
double  PercolationMax;
double  PEvap;
double  PFactor;
double  Phyllo;
double  PlantsPerHill;
double  PlotDrainageDAF;
double  PoidsSecGrain;
double  PourcRuiss;
double  PPCrit;
double  PPExp;
double  PPSens;
double  PriorityPan;
double  ProfRacIni;
double  RankLongestLeaf;
double  RelMobiliInternodeMax;
double  RelPhylloPhaseStemElong;
double  RollingBase;
double  RollingSens;
double  RootCstr;
double  RootFrontMax;
double  RootPartitMax;
double  SDJBVP;
double  SDJLevee;
double  SDJMatu1;
double  SDJMatu2;
double  SDJRPR;
double  SeuilPP;
double  SeuilRuiss;
double  SlaMax;
double  SlaMin;
double  StockIniProf;
double  StockIniSurf;
double  TBase;
double  TempSLA;
double  TilAbility;
double  TLim;
double  TOpt1;
double  TOpt2;
double  Transplanting;
double  TransplantingDepth;
double  TxAssimBVP;
double  TxAssimMatu1;
double  TxAssimMatu2;
double  TxConversion;
double  TxResGrain;
double  TxRuSurfGermi;
double  VRacBVP;
double  VRacLevee;
double  VRacMatu1;
double  VRacMatu2;
double  VRacPSP;
double  VRacRPR;
double  WaterLoggingSens;
double  WtRatioLeafSheath;

void init_parameters( const samara::ModelParameters& parameters) {
    Altitude = parameters.get<double>("altitude");
    ASScstr = parameters.get<double>("asscstr");
    AttenMitch = parameters.get<double>("attenmitch");
    BundHeight = parameters.get<double>("bundheight");
    Ca = parameters.get<double>("ca");
    CO2Cp = parameters.get<double>("co2cp");
    CO2Exp = parameters.get<double>("co2exp");
    CO2Slopetr = parameters.get<double>("co2slopetr");
    CoeffAssimSla = parameters.get<double>("coeffassimsla");
    CoefficientQ10 = parameters.get<double>("coefficientq10");
    CoeffInternodeMass = parameters.get<double>("coeffinternodemass");
    CoeffInternodeNum = parameters.get<double>("coeffinternodenum");
    CoeffLeafDeath = parameters.get<double>("coeffleafdeath");
    CoeffLeafWLRatio = parameters.get<double>("coeffleafwlratio");
    CoeffPanicleMass = parameters.get<double>("coeffpaniclemass");
    CoeffPanSinkPop = parameters.get<double>("coeffpansinkpop");
    CoeffResCapacityInternode = parameters.get<double>("coeffrescapacityinternode");
    CoeffReserveSink = parameters.get<double>("coeffreservesink");
    CoeffRootMassPerVolMax = parameters.get<double>("coeffrootmasspervolmax");
    CoeffTillerDeath = parameters.get<double>("coefftillerdeath");
    CoeffTransplantingShock = parameters.get<double>("coefftransplantingshock");
    DensityField = parameters.get<double>("densityfield");
    DensityNursery = parameters.get<double>("densitynursery");
    DEVcstr = parameters.get<double>("devcstr");
    DurationNursery = parameters.get<double>("durationnursery");
    EpaisseurProf = parameters.get<double>("epaisseurprof");
    EpaisseurSurf = parameters.get<double>("epaisseursurf");
    ExcessAssimToRoot = parameters.get<double>("excessassimtoroot");
    FTSWIrrig = parameters.get<double>("ftswirrig");
    HaunCritTillering = parameters.get<double>("hauncrittillering");
    HumFC = parameters.get<double>("humfc");
    HumPF = parameters.get<double>("humpf");
    HumSat = parameters.get<double>("humsat");
    IcTillering = parameters.get<double>("ictillering");
    InternodeLengthMax = parameters.get<double>("internodelengthmax");
    IrrigAuto = parameters.get<int>("irrigauto");
    IrrigAutoResume = parameters.get<double>("irrigautoresume");
    IrrigAutoStop = parameters.get<double>("irrigautostop");
    IrrigAutoTarget = parameters.get<double>("irrigautotarget");
    KcMax = parameters.get<double>("kcmax");
    KCritSterCold1 = parameters.get<double>("kcritstercold1");
    KCritSterCold2 = parameters.get<double>("kcritstercold2");
    KCritSterFtsw1 = parameters.get<double>("kcritsterftsw1");
    KCritSterFtsw2 = parameters.get<double>("kcritsterftsw2");
    KCritSterHeat1 = parameters.get<double>("kcritsterheat1");
    KCritSterHeat2 = parameters.get<double>("kcritsterheat2");
    KCritStressCold1 = parameters.get<double>("kcritstresscold1");
    KCritStressCold2 = parameters.get<double>("kcritstresscold2");
    Kdf = parameters.get<double>("kdf");
    KPar = parameters.get<double> ("kpar");
    KRespInternode = parameters.get<double>("krespinternode");
    KRespMaintLeaf = parameters.get<double>("krespmaintleaf");
    KRespMaintRoot = parameters.get<double>("krespmaintroot");
    KRespMaintSheath = parameters.get<double>("krespmaintsheath");
    KRespPanicle = parameters.get<double>("kresppanicle");
    KTempMaint = parameters.get<double>("ktempmaint");
    Latitude = parameters.get<double>("latitude");
    LeafLengthMax = parameters.get<double>("leaflengthmax");
    LifeSavingDrainage = parameters.get<double>("lifesavingdrainage");
    Mulch = parameters.get<double>("mulch");
    PanStructMassMax = parameters.get<double>("panstructmassmax");
    PercolationMax = parameters.get<double>("percolationmax");
    PEvap = parameters.get<double>("pevap");
    PFactor = parameters.get<double>("pfactor");
    Phyllo = parameters.get<double>("phyllo");
    PlantsPerHill = parameters.get<double>("plantsperhill");
    PlotDrainageDAF = parameters.get<double>("plotdrainagedaf");
    PoidsSecGrain = parameters.get<double>("poidssecgrain");
    PourcRuiss = parameters.get<double>("pourcruiss");
    PPCrit = parameters.get<double>("ppcrit");
    PPExp = parameters.get<double>("ppexp");
    PPSens = parameters.get<double>("ppsens");
    PriorityPan = parameters.get<double>("prioritypan");
    ProfRacIni = parameters.get<double>("profracini");
    RankLongestLeaf = parameters.get<double>("ranklongestleaf");
    RelMobiliInternodeMax = parameters.get<double>("relmobiliinternodemax");
    RelPhylloPhaseStemElong = parameters.get<double>("relphyllophasestemelong");
    RollingBase = parameters.get<double>("rollingbase");
    RollingSens = parameters.get<double>("rollingsens");
    RootCstr = parameters.get<double>("rootcstr");
    RootFrontMax = parameters.get<double>("rootfrontmax");
    RootPartitMax = parameters.get<double>("rootpartitmax");
    SDJBVP = parameters.get<double>("sdjbvp");
    SDJLevee = parameters.get<double>("sdjlevee");
    SDJMatu1 = parameters.get<double>("sdjmatu1");
    SDJMatu2 = parameters.get<double>("sdjmatu2");
    SDJRPR = parameters.get<double>("sdjrpr");
    SeuilPP = parameters.get<double>("seuilpp");
    SeuilRuiss = parameters.get<double>("seuilruiss");
    SlaMax = parameters.get<double>("slamax");
    SlaMin = parameters.get<double>("slamin");
    StockIniProf = parameters.get<double>("stockiniprof");
    StockIniSurf = parameters.get<double>("stockinisurf");
    TBase = parameters.get<double>("tbase");
    TempSLA = parameters.get<double>("tempsla");
    TilAbility = parameters.get<double>("tilability");
    TLim = parameters.get<double>("tlim");
    TOpt1 = parameters.get<double>("topt1");
    TOpt2 = parameters.get<double>("topt2");
    Transplanting = parameters.get<double>("transplanting");
    TransplantingDepth = parameters.get<double>("transplantingdepth");
    TxAssimBVP = parameters.get<double>("txassimbvp");
    TxAssimMatu1 = parameters.get<double>("txassimmatu1");
    TxAssimMatu2 = parameters.get<double>("txassimmatu2");
    TxConversion = parameters.get<double>("txconversion");
    TxResGrain = parameters.get<double>("txresgrain");
    TxRuSurfGermi = parameters.get<double>("txrusurfgermi");
    VRacBVP = parameters.get<double>("vracbvp");
    VRacLevee = parameters.get<double>("vraclevee");
    VRacMatu1 = parameters.get<double>("vracmatu1");
    VRacMatu2 = parameters.get<double>("vracmatu2");
    VRacPSP = parameters.get<double>("vracpsp");
    VRacRPR = parameters.get<double>("vracrpr");
    WaterLoggingSens = parameters.get<double>("waterloggingsens");
    WtRatioLeafSheath = parameters.get<double>("wtratioleafsheath");
}

#endif // PARAMETERS_H
