#ifndef VARIABLES_H
#define VARIABLES_H

double ApexHeight;
double ApexHeightGain;
double Assim;
double AssimNotUsed;
double AssimNotUsedCum;
double AssimPot;
double AssimSurplus;
double A_AssimSurplus;
double A_DemStructLeaf;
double A_DemStructTot;
double A_GrowthStructLeaf;
double A_GrowthStructTot;
double A_IncreaseResInternodePop;
double A_ResInternodeMobiliDay;
double CapaRDE;
double CapaREvap;
double CapaRFE;
double ChangeNurseryStatus;
double ChangePhase;
double ChangeSsPhase;
double CoeffCO2Assim;
double CoeffCO2Tr;
double CoeffStressLogging;
double Conversion;
double ConversionEff;
double CounterNursery;
double Cstr;
double CstrAssim;
double CstrCum;
double CstrMean;
double CstrPhase2;
double CstrPhase3;
double CstrPhase4;
double CstrPhase5;
double CstrPhase6;
double CulmsPerHill;
double CulmsPerHillFin;
double CulmsPerHillMax;
double CulmsPerPlant;
double CulmsPerPlantFin;
double CulmsPerPlantMax;
double CulmsPop;
double CumCarbonUsedPop;
double CumCstrPhase2;
double CumCstrPhase3;
double CumCstrPhase4;
double CumCstrPhase5;
double CumCstrPhase6;
double CumDr;
double CumEt;
double CumFTSWPhase2;
double CumFTSWPhase3;
double CumFTSWPhase4;
double CumFTSWPhase5;
double CumFTSWPhase6;
double CumGrowthPop;
double CumIcPhase2;
double CumIcPhase3;
double CumIcPhase4;
double CumIcPhase5;
double CumIcPhase6;
double CumIrrig;
double CumIrrigFin;
double CumLr;
double CumPAR;
double CumSupplyTot;
double CumTr;
double CumWReceived;
double CumWUse;
double CumWUseFin;
double DAF;
double DeadLeafdrywtPop;
double DegresDuJour;
double DegresDuJourCor;
double DemLeafAreaPlant;
double DemPanicleFillPop;
double DemResInternodePop;
double DemStructInternodePlant;
double DemStructInternodePop;
double DemStructLeafPlant;
double DemStructLeafPop;
double DemStructPaniclePlant;
double DemStructPaniclePop;
double DemStructRootPlant;
double DemStructRootPop;
double DemStructSheathPop;
double DemStructTotPop;
double Density;
double Dr;
double DryMatAboveGroundPop;
double DryMatAboveGroundPopFin;
double DryMatAboveGroundTotPop;
double DryMatPanicleTotPop;
double DryMatResInternodePop;
double DryMatResInternodePopOld;
double DryMatStructInternodePop;
double DryMatStructLeafPop;
double DryMatStructPaniclePop;
double DryMatStructRootPop;
double DryMatStructSheathPop;
double DryMatStructStemPop;
double DryMatStructTotPop;
double DryMatTotPop;
double DryMatTotPopFin;
double DryMatVegeTotPop;
double DurGermFlow;
double DurGermMat;
double DurPhase1;
double DurPhase2;
double DurPhase3;
double DurPhase4;
double DurPhase5;
double DurPhase6;
double EauDispo;
double ETM;
double ETR;
double Evap;
double EvapPot;
double FertSpikeNumPop;
double FloodwaterDepth;
double FloodwaterGain;
double FractionPlantHeightSubmer;
double FractionRootsLogged;
double FTSW;
double FtswMoy;
double FtswPhase2;
double FtswPhase3;
double FtswPhase4;
double FtswPhase5;
double FtswPhase6;
double GainRootSystSoilSurfPop;
double GainRootSystVolPop;
double GrainFillingStatus;
double GrainFillingStatusFin;
double GrainYieldPanicle;
double GrainYieldPop;
double GrainYieldPopFin;
double GrowthDryMatPop;
double GrowthPop;
double GrowthResInternodePop;
double GrowthStructDeficit;
double GrowthStructInternodePop;
double GrowthStructLeafPop;
double GrowthStructPaniclePop;
double GrowthStructRootPop;
double GrowthStructSheathPop;
double GrowthStructTotPop;
double HarvestIndex;
double HaunGain;
double HaunIndex;
double Hum;
double Ic;
double IcCum;
double IcMean;
double IcPhase2;
double IcPhase3;
double IcPhase4;
double IcPhase5;
double IcPhase6;
double IncreaseResInternodePop;
double InternodeResStatus;
double Irrigation;
double IrrigAutoDay;
double IrrigTotDay;
double Kce;
double KceReal;
double Kcl;
double Kcp;
double KcTot;
double Kr;
double KRolling;
double Lai;
double LaiDead;
double LaiFin;
double LastLeafLength;
double LastLeafLengthPot;
double LeafDeathPop;
double LIRkdf;
double LIRkdfcl;
double Lr;
double LTRkdf;
double LTRkdfcl;
double MaxLai;
double MobiliLeafDeath;
double NumPhase;
double NumSsPhase;
double NurseryStatus;
double PanicleFilDeficit;
double PanicleFilPop;
double PanicleNumPlant;
double PanicleNumPop;
double PanicleSinkPop;
double PanStructMass;
double PARIntercepte;
double PhaseStemElongation;
double PlantHeight;
double PlantLeafNumNew;
double PlantLeafNumTot;
double PlantWidth;
double ProfRu;
double RelPotLeafLength;
double ResCapacityInternodePop;
double ReservePopFin;
double ResInternodeMobiliDay;
double ResInternodeMobiliDayPot;
double RespMaintDebt;
double RespMaintTot;
double ResUtil;
double RootFront;
double RootFrontOld;
double RootMassPerVol;
double RootShootRatio;
double RootSystSoilSurfPop;
double RootSystSoilSurfPopOld;
double RootSystVolPop;
double RootSystVolPopOld;
double RUE;
double RuRac;
double RuSurf;
double SDJCorPhase4;
double SeuilCstrMortality;
double SeuilTemp;
double SeuilTempSsPhase;
double SimAnthesis50;
double SimEmergence;
double SimEndCycle;
double SimPanIni;
double SimStartGermin;
double SimStartMatu2;
double SimStartPSP;
double Sla;
double SlaMitch;
double SlaNew;
double SommeDegresJourMax;
double SpikeNumPanicle;
double SpikeNumPop;
double SterilityCold;
double SterilityDrought;
double SterilityHeat;
double SterilityTot;
double SterilityTotFin;
double StockMacropores;
double StockRac;
double StockSurface;
double StockTotal;
double StressCold;
double StRuMax;
double SumDDPhasePrec;
double SumDegreDayCor;
double SumDegresDay;
double SumPP;
double SupplyTot;
double TempLai;
double TillerDeathPop;
double Tr;
double TrEff;
double TrEffInst;
double TrPot;
double ValRDE;
double ValRFE;
double ValRSurf;
double VitesseRacinaire;
double VitesseRacinaireDay;
double VolMacropores;
double VolRelMacropores;
double WueEt;
double WueTot;

namespace variables {
void init_variables() {
    ApexHeight = 0;
    ApexHeightGain = 0;
    Assim = 0;
    AssimNotUsed = 0;
    AssimNotUsedCum = 0;
    AssimPot = 0;
    AssimSurplus = 0;
    A_AssimSurplus = 0;
    A_DemStructLeaf = 0;
    A_DemStructTot = 0;
    A_GrowthStructLeaf = 0;
    A_GrowthStructTot = 0;
    A_IncreaseResInternodePop = 0;
    A_ResInternodeMobiliDay = 0;
    CapaRDE = 0;
    CapaREvap = 0;
    CapaRFE = 0;
    ChangeNurseryStatus = 0;
    ChangePhase = 0;
    ChangeSsPhase = 0;
    CoeffCO2Assim = 0;
    CoeffCO2Tr = 0;
    CoeffStressLogging = 0;
    Conversion = 0;
    ConversionEff = 0;
    CounterNursery = 0;
    Cstr = 0;
    CstrAssim = 0;
    CstrCum = 0;
    CstrMean = 0;
    CstrPhase2 = 0;
    CstrPhase3 = 0;
    CstrPhase4 = 0;
    CstrPhase5 = 0;
    CstrPhase6 = 0;
    CulmsPerHill = 0;
    CulmsPerHillFin = 0;
    CulmsPerHillMax = 0;
    CulmsPerPlant = 0;
    CulmsPerPlantFin = 0;
    CulmsPerPlantMax = 0;
    CulmsPop = 0;
    CumCarbonUsedPop = 0;
    CumCstrPhase2 = 0;
    CumCstrPhase3 = 0;
    CumCstrPhase4 = 0;
    CumCstrPhase5 = 0;
    CumCstrPhase6 = 0;
    CumDr = 0;
    CumEt = 0;
    CumFTSWPhase2 = 0;
    CumFTSWPhase3 = 0;
    CumFTSWPhase4 = 0;
    CumFTSWPhase5 = 0;
    CumFTSWPhase6 = 0;
    CumGrowthPop = 0;
    CumIcPhase2 = 0;
    CumIcPhase3 = 0;
    CumIcPhase4 = 0;
    CumIcPhase5 = 0;
    CumIcPhase6 = 0;
    CumIrrig = 0;
    CumIrrigFin = 0;
    CumLr = 0;
    CumPAR = 0;
    CumSupplyTot = 0;
    CumTr = 0;
    CumWReceived = 0;
    CumWUse = 0;
    CumWUseFin = 0;
    DAF = 0;
    DeadLeafdrywtPop = 0;
    DegresDuJour = 0;
    DegresDuJourCor = 0;
    DemLeafAreaPlant = 0;
    DemPanicleFillPop = 0;
    DemResInternodePop = 0;
    DemStructInternodePlant = 0;
    DemStructInternodePop = 0;
    DemStructLeafPlant = 0;
    DemStructLeafPop = 0;
    DemStructPaniclePlant = 0;
    DemStructPaniclePop = 0;
    DemStructRootPlant = 0;
    DemStructRootPop = 0;
    DemStructSheathPop = 0;
    DemStructTotPop = 0;
    Density = 0;
    Dr = 0;
    DryMatAboveGroundPop = 0;
    DryMatAboveGroundPopFin = 0;
    DryMatAboveGroundTotPop = 0;
    DryMatPanicleTotPop = 0;
    DryMatResInternodePop = 0;
    DryMatResInternodePopOld = 0;
    DryMatStructInternodePop = 0;
    DryMatStructLeafPop = 0;
    DryMatStructPaniclePop = 0;
    DryMatStructRootPop = 0;
    DryMatStructSheathPop = 0;
    DryMatStructStemPop = 0;
    DryMatStructTotPop = 0;
    DryMatTotPop = 0;
    DryMatTotPopFin = 0;
    DryMatVegeTotPop = 0;
    DurGermFlow = 0;
    DurGermMat = 0;
    DurPhase1 = 0;
    DurPhase2 = 0;
    DurPhase3 = 0;
    DurPhase4 = 0;
    DurPhase5 = 0;
    DurPhase6 = 0;
    EauDispo = 0;
    ETM = 0;
    ETo = 0;
    ETR = 0;
    Evap = 0;
    EvapPot = 0;
    FertSpikeNumPop = 0;
    FloodwaterDepth = 0;
    FloodwaterGain = 0;
    FractionPlantHeightSubmer = 0;
    FractionRootsLogged = 0;
    FTSW = 0;
    FtswMoy = 0;
    FtswPhase2 = 0;
    FtswPhase3 = 0;
    FtswPhase4 = 0;
    FtswPhase5 = 0;
    FtswPhase6 = 0;
    GainRootSystSoilSurfPop = 0;
    GainRootSystVolPop = 0;
    GrainFillingStatus = 0;
    GrainFillingStatusFin = 0;
    GrainYieldPanicle = 0;
    GrainYieldPop = 0;
    GrainYieldPopFin = 0;
    GrowthDryMatPop = 0;
    GrowthPop = 0;
    GrowthResInternodePop = 0;
    GrowthStructDeficit = 0;
    GrowthStructInternodePop = 0;
    GrowthStructLeafPop = 0;
    GrowthStructPaniclePop = 0;
    GrowthStructRootPop = 0;
    GrowthStructSheathPop = 0;
    GrowthStructTotPop = 0;
    HarvestIndex = 0;
    HaunGain = 0;
    HaunIndex = 0;
    HMoyCalc = 0;
    Hum = 0;
    Ic = 0;
    IcCum = 0;
    IcMean = 0;
    IcPhase2 = 0;
    IcPhase3 = 0;
    IcPhase4 = 0;
    IcPhase5 = 0;
    IcPhase6 = 0;
    IncreaseResInternodePop = 0;
    InternodeResStatus = 0;
    Irrigation = 0;
    IrrigAutoDay = 0;
    IrrigTotDay = 0;
    Kce = 0;
    KceReal = 0;
    Kcl = 0;
    Kcp = 0;
    KcTot = 0;
    Kr = 0;
    KRolling = 0;
    Lai = 0;
    LaiDead = 0;
    LaiFin = 0;
    LastLeafLength = 0;
    LastLeafLengthPot = 0;
    LatRad = 0;
    LeafDeathPop = 0;
    LIRkdf = 0;
    LIRkdfcl = 0;
    Lr = 0;
    LTRkdf = 0;
    LTRkdfcl = 0;
    MaxLai = 0;
    MobiliLeafDeath = 0;
    NumPhase = 0;
    NumSsPhase = 0;
    NurseryStatus = 0;
    PanicleFilDeficit = 0;
    PanicleFilPop = 0;
    PanicleNumPlant = 0;
    PanicleNumPop = 0;
    PanicleSinkPop = 0;
    PanStructMass = 0;
    PARIntercepte = 0;
    PhaseStemElongation = 0;
    PlantHeight = 0;
    PlantLeafNumNew = 0;
    PlantLeafNumTot = 0;
    PlantWidth = 0;
    ProfRu = 0;
    RelPotLeafLength = 0;
    ResCapacityInternodePop = 0;
    ReservePopFin = 0;
    ResInternodeMobiliDay = 0;
    ResInternodeMobiliDayPot = 0;
    RespMaintDebt = 0;
    RespMaintTot = 0;
    ResUtil = 0;
    RootFront = 0;
    RootFrontOld = 0;
    RootMassPerVol = 0;
    RootShootRatio = 0;
    RootSystSoilSurfPop = 0;
    RootSystSoilSurfPopOld = 0;
    RootSystVolPop = 0;
    RootSystVolPopOld = 0;
    RUE = 0;
    RuRac = 0;
    RuSurf = 0;
    SDJCorPhase4 = 0;
    SeuilCstrMortality = 0;
    SeuilTemp = 0;
    SeuilTempSsPhase = 0;
    SimAnthesis50 = 0;
    SimEmergence = 0;
    SimEndCycle = 0;
    SimPanIni = 0;
    SimStartGermin = 0;
    SimStartMatu2 = 0;
    SimStartPSP = 0;
    Sla = 0;
    SlaMitch = 0;
    SlaNew = 0;
    SommeDegresJourMax = 0;
    SpikeNumPanicle = 0;
    SpikeNumPop = 0;
    SterilityCold = 0;
    SterilityDrought = 0;
    SterilityHeat = 0;
    SterilityTot = 0;
    SterilityTotFin = 0;
    StockMacropores = 0;
    StockRac = 0;
    StockSurface = 0;
    StockTotal = 0;
    StressCold = 0;
    StRuMax = 0;
    SumDDPhasePrec = 0;
    SumDegreDayCor = 0;
    SumDegresDay = 0;
    SumPP = 0;
    SunDistance = 0;
    SupplyTot = 0;
    TempLai = 0;
    TillerDeathPop = 0;
    Tr = 0;
    TrEff = 0;
    TrEffInst = 0;
    TrPot = 0;
    ValRDE = 0;
    ValRFE = 0;
    ValRSurf = 0;
    VPDCalc = 0;
    VitesseRacinaire = 0;
    VitesseRacinaireDay = 0;
    VolMacropores = 0;
    VolRelMacropores = 0;
    WueEt = 0;
    WueTot = 0;

}

void reset() {
    CulmsPerPlant = 0;
    CulmsPerHill = 0;
    CulmsPop = 0;
    GrainYieldPop = 0;
    DryMatStructLeafPop = 0;
    DryMatStructSheathPop = 0;
    DryMatStructRootPop = 0;
    DryMatStructInternodePop = 0;
    DryMatResInternodePop = 0;
    DryMatStructPaniclePop = 0;
    DryMatStructStemPop = 0;
    DryMatStructTotPop = 0;
    DryMatVegeTotPop = 0;
    DryMatPanicleTotPop = 0;
    DryMatAboveGroundPop = 0;
    DryMatTotPop = 0;
    HarvestIndex = 0;
    PanicleNumPop = 0;
    PanicleNumPlant = 0;
    GrainYieldPanicle = 0;
    SpikeNumPop = 0;
    SpikeNumPanicle = 0;
    FertSpikeNumPop = 0;
    GrainFillingStatus = 0;
    PhaseStemElongation = 0;
    Sla = 0;
    HaunIndex = 0;
    ApexHeight = 0;
    PlantHeight = 0;
    PlantWidth = 0;
    VitesseRacinaireDay = 0;
    Kcl = 0;
    KRolling = 0;
    LIRkdfcl = 0;
    LTRkdfcl = 1;
    AssimPot = 0;
    Assim = 0;
    RespMaintTot = 0;
    SupplyTot = 0;
    AssimSurplus = 0;
    AssimNotUsed = 0;
    AssimNotUsedCum = 0;
    TillerDeathPop = 0;
    DeadLeafdrywtPop = 0;
    ResCapacityInternodePop = 0;
    InternodeResStatus = 0;
    Cstr = 0;
    FTSW = 0;
    DryMatAboveGroundTotPop = 0;
}

}
#endif // VARIABLES_H
