#ifndef PARAMETERS_H
#define PARAMETERS_H
#include "ModelParameters.hpp"
double Altitude;
double ASScstr;
double AttenMitch;
double BundHeight;
double Ca;
double CO2Cp;
double CO2Exp;
double CO2Slopetr;
double CoeffAssimSla;
double CoefficientQ10;
double CoeffInternodeMass;
double CoeffInternodeNum;
double CoeffLeafDeath;
double CoeffLeafWLRatio;
double CoeffPanicleMass;
double CoeffPanSinkPop;
double CoeffResCapacityInternode;
double CoeffReserveSink;
double CoeffRootMassPerVolMax;
double CoeffTillerDeath;
double CoeffTransplantingShock;
double DensityField;
double DensityNursery;
double DEVcstr;
double DurationNursery;
double EpaisseurProf;
double EpaisseurSurf;
double ExcessAssimToRoot;
double FTSWIrrig;
double HaunCritTillering;
double HumFC;
double HumPF;
double HumSat;
double IcTillering;
double InternodeLengthMax;
double IrrigAuto;
double IrrigAutoResume;
double IrrigAutoStop;
double IrrigAutoTarget;
double KcMax;
double KCritSterCold1;
double KCritSterCold2;
double KCritSterFtsw1;
double KCritSterFtsw2;
double KCritSterHeat1;
double KCritSterHeat2;
double KCritStressCold1;
double KCritStressCold2;
double Kdf;
double KPar;
double KRespInternode;
double KRespMaintLeaf;
double KRespMaintRoot;
double KRespMaintSheath;
double KRespPanicle;
double KTempMaint;
double Latitude;
double LeafLengthMax;
double LifeSavingDrainage;
double Mulch;
double PanStructMassMax;
double PercolationMax;
double PEvap;
double PFactor;
double Phyllo;
double PlantsPerHill;
double PlotDrainageDAF;
double PoidsSecGrain;
double PourcRuiss;
double PPCrit;
double PPExp;
double PPSens;
double PriorityPan;
double ProfRacIni;
double RankLongestLeaf;
double RelMobiliInternodeMax;
double RelPhylloPhaseStemElong;
double RollingBase;
double RollingSens;
double RootCstr;
double RootFrontMax;
double RootPartitMax;
double SDJBVP;
double SDJLevee;
double SDJMatu1;
double SDJMatu2;
double SDJRPR;
double SeuilPP;
double SeuilRuiss;
double SlaMax;
double SlaMin;
double StockIniProf;
double StockIniSurf;
double TBase;
double TempSLA;
double TilAbility;
double TLim;
double TOpt1;
double TOpt2;
double Transplanting;
double TransplantingDepth;
double TxAssimBVP;
double TxAssimMatu1;
double TxAssimMatu2;
double TxConversion;
double TxResGrain;
double TxRuSurfGermi;
double VRacBVP;
double VRacLevee;
double VRacMatu1;
double VRacMatu2;
double VRacPSP;
double VRacRPR;
double WaterLoggingSens;
double WtRatioLeafSheath;

void init_parameters( const samara::ModelParameters& parameters) {
    Altitude = parameters.getDouble("altitude");
    ASScstr = parameters.getDouble("asscstr");
    AttenMitch = parameters.getDouble("attenmitch");
    BundHeight = parameters.getDouble("bundheight");
    Ca = parameters.getDouble("ca");
    CO2Cp = parameters.getDouble("co2cp");
    CO2Exp = parameters.getDouble("co2exp");
    CO2Slopetr = parameters.getDouble("co2slopetr");
    CoeffAssimSla = parameters.getDouble("coeffassimsla");
    CoefficientQ10 = parameters.getDouble("coefficientq10");
    CoeffInternodeMass = parameters.getDouble("coeffinternodemass");
    CoeffInternodeNum = parameters.getDouble("coeffinternodenum");
    CoeffLeafDeath = parameters.getDouble("coeffleafdeath");
    CoeffLeafWLRatio = parameters.getDouble("coeffleafwlratio");
    CoeffPanicleMass = parameters.getDouble("coeffpaniclemass");
    CoeffPanSinkPop = parameters.getDouble("coeffpansinkpop");
    CoeffResCapacityInternode = parameters.getDouble("coeffrescapacityinternode");
    CoeffReserveSink = parameters.getDouble("coeffreservesink");
    CoeffRootMassPerVolMax = parameters.getDouble("coeffrootmasspervolmax");
    CoeffTillerDeath = parameters.getDouble("coefftillerdeath");
    CoeffTransplantingShock = parameters.getDouble("coefftransplantingshock");
    DensityField = parameters.getDouble("densityfield");
    DensityNursery = parameters.getDouble("densitynursery");
    DEVcstr = parameters.getDouble("devcstr");
    DurationNursery = parameters.getDouble("durationnursery");
    EpaisseurProf = parameters.getDouble("epaisseurprof");
    EpaisseurSurf = parameters.getDouble("epaisseursurf");
    ExcessAssimToRoot = parameters.getDouble("excessassimtoroot");
    FTSWIrrig = parameters.getDouble("ftswirrig");
    HaunCritTillering = parameters.getDouble("hauncrittillering");
    HumFC = parameters.getDouble("humfc");
    HumPF = parameters.getDouble("humpf");
    HumSat = parameters.getDouble("humsat");
    IcTillering = parameters.getDouble("ictillering");
    InternodeLengthMax = parameters.getDouble("internodelengthmax");
    IrrigAuto = parameters.getInt("irrigauto");
    IrrigAutoResume = parameters.getDouble("irrigautoresume");
    IrrigAutoStop = parameters.getDouble("irrigautostop");
    IrrigAutoTarget = parameters.getDouble("irrigautotarget");
    KcMax = parameters.getDouble("kcmax");
    KCritSterCold1 = parameters.getDouble("kcritstercold1");
    KCritSterCold2 = parameters.getDouble("kcritstercold2");
    KCritSterFtsw1 = parameters.getDouble("kcritsterftsw1");
    KCritSterFtsw2 = parameters.getDouble("kcritsterftsw2");
    KCritSterHeat1 = parameters.getDouble("kcritsterheat1");
    KCritSterHeat2 = parameters.getDouble("kcritsterheat2");
    KCritStressCold1 = parameters.getDouble("kcritstresscold1");
    KCritStressCold2 = parameters.getDouble("kcritstresscold2");
    Kdf = parameters.getDouble("kdf");
    KPar = parameters.getDouble ("kpar");
    KRespInternode = parameters.getDouble("krespinternode");
    KRespMaintLeaf = parameters.getDouble("krespmaintleaf");
    KRespMaintRoot = parameters.getDouble("krespmaintroot");
    KRespMaintSheath = parameters.getDouble("krespmaintsheath");
    KRespPanicle = parameters.getDouble("kresppanicle");
    KTempMaint = parameters.getDouble("ktempmaint");
    Latitude = parameters.getDouble("latitude");
    LeafLengthMax = parameters.getDouble("leaflengthmax");
    LifeSavingDrainage = parameters.getDouble("lifesavingdrainage");
    Mulch = parameters.getDouble("mulch");
    PanStructMassMax = parameters.getDouble("panstructmassmax");
    PercolationMax = parameters.getDouble("percolationmax");
    PEvap = parameters.getDouble("pevap");
    PFactor = parameters.getDouble("pfactor");
    Phyllo = parameters.getDouble("phyllo");
    PlantsPerHill = parameters.getDouble("plantsperhill");
    PlotDrainageDAF = parameters.getDouble("plotdrainagedaf");
    PoidsSecGrain = parameters.getDouble("poidssecgrain");
    PourcRuiss = parameters.getDouble("pourcruiss");
    PPCrit = parameters.getDouble("ppcrit");
    PPExp = parameters.getDouble("ppexp");
    PPSens = parameters.getDouble("ppsens");
    PriorityPan = parameters.getDouble("prioritypan");
    ProfRacIni = parameters.getDouble("profracini");
    RankLongestLeaf = parameters.getDouble("ranklongestleaf");
    RelMobiliInternodeMax = parameters.getDouble("relmobiliinternodemax");
    RelPhylloPhaseStemElong = parameters.getDouble("relphyllophasestemelong");
    RollingBase = parameters.getDouble("rollingbase");
    RollingSens = parameters.getDouble("rollingsens");
    RootCstr = parameters.getDouble("rootcstr");
    RootFrontMax = parameters.getDouble("rootfrontmax");
    RootPartitMax = parameters.getDouble("rootpartitmax");
    SDJBVP = parameters.getDouble("sdjbvp");
    SDJLevee = parameters.getDouble("sdjlevee");
    SDJMatu1 = parameters.getDouble("sdjmatu1");
    SDJMatu2 = parameters.getDouble("sdjmatu2");
    SDJRPR = parameters.getDouble("sdjrpr");
    SeuilPP = parameters.getDouble("seuilpp");
    SeuilRuiss = parameters.getDouble("seuilruiss");
    SlaMax = parameters.getDouble("slamax");
    SlaMin = parameters.getDouble("slamin");
    StockIniProf = parameters.getDouble("stockiniprof");
    StockIniSurf = parameters.getDouble("stockinisurf");
    TBase = parameters.getDouble("tbase");
    TempSLA = parameters.getDouble("tempsla");
    TilAbility = parameters.getDouble("tilability");
    TLim = parameters.getDouble("tlim");
    TOpt1 = parameters.getDouble("topt1");
    TOpt2 = parameters.getDouble("topt2");
    Transplanting = parameters.getDouble("transplanting");
    TransplantingDepth = parameters.getDouble("transplantingdepth");
    TxAssimBVP = parameters.getDouble("txassimbvp");
    TxAssimMatu1 = parameters.getDouble("txassimmatu1");
    TxAssimMatu2 = parameters.getDouble("txassimmatu2");
    TxConversion = parameters.getDouble("txconversion");
    TxResGrain = parameters.getDouble("txresgrain");
    TxRuSurfGermi = parameters.getDouble("txrusurfgermi");
    VRacBVP = parameters.getDouble("vracbvp");
    VRacLevee = parameters.getDouble("vraclevee");
    VRacMatu1 = parameters.getDouble("vracmatu1");
    VRacMatu2 = parameters.getDouble("vracmatu2");
    VRacPSP = parameters.getDouble("vracpsp");
    VRacRPR = parameters.getDouble("vracrpr");
    WaterLoggingSens = parameters.getDouble("waterloggingsens");
    WtRatioLeafSheath = parameters.getDouble("wtratioleafsheath");
}

#endif // PARAMETERS_H
