// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "rsamara_types.hpp"
#include <Rcpp.h>

using namespace Rcpp;

// getParameters_from_database
List getParameters_from_database(Rcpp::String name);
RcppExport SEXP rsamara_getParameters_from_database(SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(getParameters_from_database(name));
    return rcpp_result_gen;
END_RCPP
}
// getMeteo_from_database
List getMeteo_from_database(Rcpp::String name);
RcppExport SEXP rsamara_getMeteo_from_database(SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(getMeteo_from_database(name));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_init_from_database
XPtr < Context > rcpp_init_from_database(Rcpp::String name);
RcppExport SEXP rsamara_rcpp_init_from_database(SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::String >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_init_from_database(name));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_run
List rcpp_run(SEXP handle);
RcppExport SEXP rsamara_rcpp_run(SEXP handleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type handle(handleSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_run(handle));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_run_from_dataframe
List rcpp_run_from_dataframe(List dfParameters, List dfMeteo);
RcppExport SEXP rsamara_rcpp_run_from_dataframe(SEXP dfParametersSEXP, SEXP dfMeteoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dfParameters(dfParametersSEXP);
    Rcpp::traits::input_parameter< List >::type dfMeteo(dfMeteoSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_run_from_dataframe(dfParameters, dfMeteo));
    return rcpp_result_gen;
END_RCPP
}
